### ISSUE TITLE
GeoShapeConstants class in the new elasticsearch 1.0 branch

### ISSUE THREAD

**Issue by vladshup** [ncolomer/elasticsearch-osmosis-plugin#11]
Then recompile with elasticsearch 0.90.10 and it work fine with last release, but not work with beta line 1.0.0.Beta1, 1.0.0.Beta2 of elasticsearch.
During compilation with  1.0.0.Beta1, 1.0.0.Beta2 error:
[ERROR] /root/osmosis/src/main/java/org/openstreetmap/osmosis/plugin/elasticsearch/model/shape/ESShape.java:[7,35] cannot find symbol
symbol  : class GeoShapeConstants
location: package org.elasticsearch.common.geo
[ERROR] /root/osmosis/src/main/java/org/openstreetmap/osmosis/plugin/elasticsearch/model/shape/ESShape.java:[203,46] package GeoShapeConstants does not exist

**Comment by ncolomer** [comment]
Thanks for the feedback. This sounds like I'll have to open a new default v1.0 branch to maintain compatibility with v0.90.
